version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: monthly
          day: 10
          time: '00:05'
          timezone: Europe/Berlin
      open-pull-requests-limit: 5
      assignees:
          - UncleSamSwiss
      versioning-strategy: increase
      cooldown:
          default-days: 7

    - package-ecosystem: github-actions
      directory: '/'
      schedule:
          interval: monthly
          day: 10
          time: '00:05'
          timezone: Europe/Berlin
      open-pull-requests-limit: 5
      assignees:
          - UncleSamSwiss
